### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by blairmacintyre** [immersive-web/anchors#15]
In the explainer you say

> The main difference is that while ARKit uses the concept of an anchor to represent the identified real world object (that happens to have a pose) while this explainer uses the term anchor to only represent poses. Basic arbitrary ARAnchor (1) in ARKit would be equivalent of the concept of an anchor in this explainer. The representation of the real world objects is out of the scope of this explainer. This differentiation between the concept of an anchor in ARKit and in the scope of this explainer is subtle but important.

I agree we aren't defining more than the basic anchor, but this seems too much.  Would it be possibly to say something along the lines that these other anchors are subclasses of the basic anchor in ARKit, and we anticipate that other APIs would use and extend anchors in the future.  Because, that's what I expect.

In fact, in the very next section you say just that.  So these two sections should be massaged for consistency.

**Comment by blairmacintyre** [comment]
Similarly, further down:
>They are **not** intended to track moving objects.

This should be removed, as it's already been clarified and expressed that this is a starting point and there could eventually be anchor types that include that capability.  Just not yet.

**Comment by judax** [comment]
I think that is the purpose of the scope in the current version of the explainer: correctly set the expectations on what the current status is. There have been discussions about the Trackable and Anchor concepts and their relationships and I think there is still not a clear path: Are trackables a specific type of anchors or different classes that anchors are referencing? Still, if there is inconsistency in the current version of the explainer, it is important to correct it.

**Comment by blairmacintyre** [comment]
I completely agree we need to make the scope clear, and not asserting other things _will_ but a subclass of anchor.  

I'll have a go at cleaning up the language and submit a PR.

**Comment by judax** [comment]
Do you feel that this issue should be kept open after your PR #16 has landed?

**Comment by blairmacintyre** [comment]
nope, I think it can be closed.
