### ISSUE TITLE
Anchors should have a unique UID

### ISSUE THREAD

**Issue by blairmacintyre** [immersive-web/anchors#18]
In my experiments with implementing Anchors, I've added a unique string id to each  anchor, which makes it easy to use Javascript Map's to keep track of the Anchors I have.  

Would like to have a property `anchor.uid` on the anchor to retrieve a unique string for each object.

(In my implementation on iOS, I either use ARKit UID's for their anchors, or generate my own for synthetic Anchors I create on top of ARKit's anchors)

**Comment by bialpio** [comment]
I'd like to avoid adding more attributes if they are not strictly needed. JS should already allow indexing maps with the XRAnchor object itself, synthetic UUID should not be needed. This should just work:
```
let anchor = ...; // Anchor created via XRFrame.createAnchor(...)
                  // or XRHitTestResult.createAnchor(...)
let anchorMap = new Map();

anchorMap[anchor] = {
  // ... some additional information that the app wants to associate with the anchor ...
};
```

Closing the issue now, please reopen if you disagree.

**Comment by raviramachandra** [comment]
Is the current XRAnchor IDL extendable ? If in near future we allow anchors to persist, the current unique XRAnchor object based model will not work. How would the spec evolve to handle at the least across session Anchors in future ? @bialpio or @blairmacintyre  

Just as a reference our very early stage Anchor like APIs : https://magicleaphelio.com/WebAPI/docs/web-xr.html
