### ISSUE TITLE
Anchors in VR

### ISSUE THREAD

**Issue by blairmacintyre** [immersive-web/anchors#2]
I added an issue on the webxr repo to talk about anchors in VR.

https://github.com/immersive-web/webxr/issues/337

**Comment by NellWaliczek** [comment]
The referenced issue was closed in the main webxr repo based on the work being done in this repo.  It also seems like this is a dup of #8 .  If you don't object, @blairmacintyre , it seems like we should probably close this issue.

**Comment by TrevorFSmith** [comment]
Agreed. Let's move this conversation to #8.
