### ISSUE TITLE
Consider merging XRAnchor and its space into an XRAnchorSpace

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/anchors#47]
This isn't something I feel strongly about, but overall it might be better to have an interface of

```webidl
interface XRAnchorSpace: XRSpace {
    void delete();
}
```

since overall spaces are just really representations of tracked objects. We do something similar in [the hands input API](https://github.com/immersive-web/webxr-hands-input/blob/master/explainer.md#appendix-proposed-idl) where the joints are just `XRJointSpace`s.

Apologies for posting this rather late in the process, this occurred to me after I noticed https://github.com/immersive-web/anchors/issues/46.

**Comment by bialpio** [comment]
I think we have discussed this in #17 & decided to stick with "has-a" approach. My 2 cents are that to me the "has-a" approach is a bit more flexible since it more firmly separates the 2 concepts & we can potentially extend the interfaces independently from each other.

**Comment by Manishearth** [comment]
Seems fair.
