### ISSUE TITLE
Should XRHitTestResult.createAnchor() have the pose argument?

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/anchors#48]
It's not clear to me that it is useful.

Its semantics are also not specified that well.

**Comment by blairmacintyre** [comment]
Yes, I think so.  If I have a want to put an anchor 0.15m in front of the controller (i.e., at the tip of a tool), I would createAnchor() with the pose being 0.15m in some direction from the controllerspace, I think.

**Comment by bialpio** [comment]
The use case I had in mind was creating an anchor that is relative to a hit test result but at a fixed offset from it. It may not be strictly necessary since the app could maintain the fixed offset from an anchor itself.

**Comment by Manishearth** [comment]
@blairmacintyre right, I'm not dsputing this for  `XRFrame.getAnchor()`, it's the one on hit test results I'm concerned about, especially because of how hit test coordinate spaces work. It seems better for the app to keep track of this.

**Comment by bialpio** [comment]
Agreed, let's remove it since it does not extend the capabilities of the API. Besides, it's way easier to remove it now and add it back later.

**Comment by Manishearth** [comment]
Thank you! :smiley_cat:
