### ISSUE TITLE
Experimental implementation questions about integrating hit-testing and anchors

### ISSUE THREAD

**Issue by TrevorFSmith** [immersive-web/anchors#5]
I'm working to update Mozilla's WebXR Viewer to the latest draft of the WebXR Device API. That works well, thanks in large part to @jsantell!

Since we use the WebXR Viewer mostly as a test platform for AR experiments, I also need to implement hit testing and anchors, backed by ARKit.

**Question 1:**

ARKit accepts only normalized x,y screen coordinates, not arbitrary origin and 
directions for hit-testing, so we need some pattern for requesting a hit test with that data. In our previous API we had two methods on the XRSession, one for requesting with an arbitrary origin and direction (which always failed) and one for requesting using normalized screen coordinates.

What are others thinking about to solve this problem?

**Question 2:**

For this version, I'm just implementing the simplest possible anchor, which is a pose that is updated over time using ARKit data. Right now I have the anchor class extend XRCoordinateSystem and it is returned as an attribute on XRHitResult.

Is that in line with others' thinking? Is XRFrameOfReference more appropriate?

**Comment by ddorwin** [comment]
Q1 is discussed in https://github.com/immersive-web/hit-test/issues/7. However, @lincolnfrog gave updated thinking in the CG call. Very briefly, 3D hit-test can be implemented on top of a 2D screen coordinates API, and Chrome did this for ARCore.

For Q2, I think @judax has an IDL proposal, but it doesn't look like it was published.

**Comment by TrevorFSmith** [comment]
Note: In the most recent AR call we discussed changing the hit testing API to use input sources instead of arbitrary origin/direction pairs to avoid the privacy risk of a web app hit testing the environment to build a point cloud of sorts, regardless of whether the user has given permission for that level of environment data.

**Comment by TrevorFSmith** [comment]
My questions were addressed in the AR call (see notes).
