### ISSUE TITLE
Small issue on `README.md` and `explainer.md`?

### ISSUE THREAD

**Issue by akyeww** [immersive-web/anchors#61]
Hi, just some questions related to docs.

1. README.md
Currently, the link for Explainer in README points to master branch's. Maybe update it to point to main branch's or use the relative path?

2. explainer.md
At the last part of the Explainer about sample code for [`Updating anchors`](https://github.com/immersive-web/anchors/blob/main/explainer.md#updating-anchors). I'm thinking it's a typo, shouldn't `xrFrame` be `frame` instead?
```
  ...
  
  for(const anchor of trackedAnchors) {
    // Query most recent pose of the anchor relative to some reference space:
    const pose = xrFrame.getPose(anchor.anchorSpace, referenceSpace);
  }

  ...
```

**Comment by himorin** [comment]
added #62 for 1).

**Comment by bialpio** [comment]
Thanks for catching this, should be fixed now! Closing the issue.
