### ISSUE TITLE
Attach plane models to surfaces for occlusion and collision detection

### ISSUE THREAD

**Issue by Simon1059770342** [immersive-web/anchors#72]
Is it possible to attach virtual plane models to surfaces for occlusion and collision detection from other virtual models? 
if so, then how to achieve this gold?
Example as：
- I place a virtual kitty in AR space near a real table, and then I move to somewhere causing my sight blocked by an real table. 
- What I expect to see is part of that kitty, but actually is the whole virtual object.
THX for your time to help me!

**Comment by AdaRoseCannon** [comment]
As of today people are usually solving this with the Depth API.

This isn't really the place for code support though, perhaps try
https://discourse.threejs.org/

Ada

**Comment by Simon1059770342** [comment]
Thanks a Lot! I will ask this WebXR question on your shared platform of three.js!
