### ISSUE TITLE
Top view map of SLAM

### ISSUE THREAD

**Issue by Simon1059770342** [immersive-web/anchors#74]
When running SLAM in WebXR, is it possible to gain a a top view plane map of object in the environment from SLAM result?
![image](https://user-images.githubusercontent.com/44942804/162424797-6be72403-19e5-48e6-9a46-880223613007.png)
![image](https://user-images.githubusercontent.com/44942804/162424954-a17d0a2e-18c7-4611-b5c2-7abbd14bd5a9.png)

**Comment by AdaRoseCannon** [comment]
Not without using hit-test to place an anchor at each corner of the room.

For security sake we don't expose full 3D information. This is unrelated to Anchors and more related to [real world geometry](https://github.com/immersive-web/real-world-geometry).

WebXR Anchors are just for maintaining the locations of single points.

**Comment by Simon1059770342** [comment]
THX!
