### ISSUE TITLE
Should anchor creation be used in VR?

### ISSUE THREAD

**Issue by judax** [immersive-web/anchors#8]
This topic was included in the explainer as an open question. It has also come up in the community group calls a couple of times and I am not sure if there was some closure to it that has been correctly captured so I decided to move it to an issue instead. Please, feel free to comment on it.

Retionale: Anchors could never update in VR scenarios but they provide positive features to the overall WebXR spec. In one hand, they may get developers to be aware of the importance of using anchors in general while developing for XR. They may provide more functionality when sharing and persistency are also proposed in the spec. Would it be interesting to use anchors in VR too? Should they be available in a VR session?

**Comment by blairmacintyre** [comment]
Why could they never update?  Current VR setups (fixed, limited area with no world understanding) would not update.  But it's pretty easy to imagine systems with SLAM-like inside-out tracking having anchors that update, as the space adjusts, IF the anchors are there.  Windows MR could, in theory, do this.

Especially if an app wants to work in both AR and VR, it might be reasonable for the app to want to create anchors in the VR case so that other parts of their app work the same in both case. 

I'd want someone from Oculus or Valve (or the Microsoft MR / VR team) to chime in though.

**Comment by NellWaliczek** [comment]
@thetuvix I vaguely recall you saying something about this?  And that developers were actually finding value of anchors in VR setups that used inside-out tracking... Am I remembering that right?

**Comment by thetuvix** [comment]
Indeed, Microsoft is currently shipping a "VR system" in which free-space anchors update independently.

The shipping Windows Mixed Reality desktop VR headset peripherals use the same inside-out tracking technology that powers HoloLens.  While most users would indeed trace out a room boundary and stay within a `"bounded"` stage with a single origin, others have hooked up their headsets to backpack PCs, giving them free mobility through much larger spaces.  Obviously, at that point, it would be up to unbounded content to help users avoid obstacles in other ways - however, while roaming large spaces, free-space anchors placed by apps will update independently, just as they do on HoloLens.

This is my primary concern with any naming in the API that uses the term "AR" as if it is equivalent to "environment understanding" or the "unbounded frame of reference".  As devices from all vendors become more capable, the clean VR vs. AR buckets we have today will all blur together. (that's exactly why we're all building one unified WebXR API!)  It's up to us to be disciplined in the API design to ensure we always describe the precise feature in question.  `XREnvironmentBlendMode` is a great start here - next up is bikeshedding on `"immersive-ar"` :smile:

**Comment by bialpio** [comment]
Closing this issue. In the current specification draft, anchors feature can be requested at session creation and there is nothing preventing implementations to support anchors in `"immersive-vr"` sessions.
